/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HolderDetails.java
 *
 * Created on Dec 14, 2015, 1:48:51 PM
 */

package zetainsuranceagency;


import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author d2
 */
public class HolderDetails extends javax.swing.JFrame {

    /** Creates new form HolderDetails */
    public HolderDetails() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        frame = new javax.swing.JInternalFrame();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N

        jButton2.setText("Modify Policy");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        frame.setVisible(true);

        javax.swing.GroupLayout frameLayout = new javax.swing.GroupLayout(frame.getContentPane());
        frame.getContentPane().setLayout(frameLayout);
        frameLayout.setHorizontalGroup(
            frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        frameLayout.setVerticalGroup(
            frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButton3.setText("View Premium Count");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Leave Zeta Insurance");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setText("Modify Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton5.setText("Log Out");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Contact Our 24x7 Assisstance");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("POLICY HOLDER'S PAGE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90)
                        .addComponent(frame, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(frame, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(133, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
         
        String a=exe.pno,nm;
        try
       {
         Class.forName("com.mysql.jdbc.Driver");
         Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/zetains","root","root");
         Statement sm=con.createStatement();
         String s="Select name from policyholders where pno='"+a+"';";
         ResultSet rs=sm.executeQuery(s);
         while(rs.next())
         {
             nm=rs.getString(1);
             jLabel1.setText("Welcome "+nm+" What do you want to do?");
         }
       }
        catch(Exception e)
            
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
       
    }//GEN-LAST:event_formWindowGainedFocus

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  exe.back="holder";
        Object[] possibilities = {"<Select>","Personal Details", "Residential Details", "Business Details","Bank Details"};
String s = (String)JOptionPane.showInputDialog(frame, "Please Select the details to be edited","Edit Details",JOptionPane.PLAIN_MESSAGE,null,possibilities,"<Select>");
if ((s.equalsIgnoreCase("Personal Details")))
{
    this.setVisible(false);
    new EditPerDet().setVisible(true);
}
if ((s.equalsIgnoreCase("Residential Details")))
{
    this.setVisible(false);
    new EditResDet().setVisible(true);return;
}
if ((s.equalsIgnoreCase("Business Details")))
{
    this.setVisible(false);
    new EditBusDet().setVisible(true);return;
}

 if ((s.equalsIgnoreCase("Bank Details")))
{
    this.setVisible(false);
    new EditBankDet().setVisible(true);return;
}

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     Object[] obj={"YES","NO"};
        int d=JOptionPane.showOptionDialog(frame,"Do you want to see our other policies","Dialog",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,obj,obj[0]);
      if(d==JOptionPane.YES_OPTION)
      {
          this.setVisible(false);
          new ViewPolicies().setVisible(true);
          exe.back="hd";
      }
  if(d==JOptionPane.NO_OPTION)
      {
          
          Object[] possibilities = {"<Select>","POL1", "POL2", "POL3","POL4","POL5"};
String s = (String)JOptionPane.showInputDialog(frame, "Please Select your New Policy","Edit Policy",JOptionPane.PLAIN_MESSAGE,null,possibilities,"<Select>");

String tno=exe.pno;
         String tc=s.substring(3);
         String pno;
         int i=0;
        try
       {
         Class.forName("com.mysql.jdbc.Driver");
         Connection cont=DriverManager.getConnection("jdbc:mysql://localhost:3306/zetains","root","root");
         Statement sm=cont.createStatement();
         String m="Select count(*) from policyholders where pno like 'p"+tc+"%';";
         ResultSet rs=sm.executeQuery(m);
         while(rs.next())
         {
             i=rs.getInt(1);
         }
         rs.close();
         if(i>=100)
           pno="P"+tc+Integer.toString(++i);
       else if(i>=10&&i<100)
           pno="P"+tc+"0"+Integer.toString(++i);
       else
           pno="P"+tc+"00"+Integer.toString(++i);
           Statement s1=cont.createStatement();
           String sq="update policyholders set pno='"+pno+"' where pno='"+tno+"';";
           s1.executeUpdate(sq);
           
           
           
           Object[] obj2={"OK","Cancel"};
           int r=JOptionPane.showOptionDialog(frame,"Details Updated.Your New Unique Policy Number(UPN) is "+pno+". Please press OK to Continue","Dialog",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,obj2,obj2[0]); 
       exe.pno=pno;
       }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
      }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try
       {
         Class.forName("com.mysql.jdbc.Driver");
         Connection cont=DriverManager.getConnection("jdbc:mysql://localhost:3306/zetains","root","root");
         Statement sm=cont.createStatement();
         String s1="Select Premium from policyholders where pno='"+exe.pno+"';";
         ResultSet rs=sm.executeQuery(s1);
         while(rs.next())
         {
             JOptionPane.showMessageDialog(null,"You have paid "+rs.getString(1)+" Premiums");
         }
       }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try
       {
         Class.forName("com.mysql.jdbc.Driver");
         Connection cont=DriverManager.getConnection("jdbc:mysql://localhost:3306/zetains","root","root");
         Statement sm=cont.createStatement();
         String s1="delete from policyholders where pno='"+exe.pno+"';";
        sm.executeUpdate(s1);
        JOptionPane.showMessageDialog(null,"Your account has been successfully removed. Our Agent would contact you as soon as possble for your leaving our agency");
        this.setVisible(false);
        new HolderLogin().setVisible(true);
       }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       JOptionPane.showMessageDialog(this,"You Have Been successfully logged out");
       this.setVisible(false);
       new HolderLogin().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         JOptionPane.showMessageDialog(this,"For 24x7 assisstance Contact:\n Narain Ji Srivastava \n +919415482084 \n NarainJi@zetainsurance.com");
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HolderDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame frame;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables

}
